services:
  db:
    image: postgres:17.8-alpine3.22
    container_name: csharp-test-pgsql
    restart: unless-stopped
    shm_size: 128mb
    ports:
      - "55432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: dumbo
